### PR TITLE
A set of additions

### PR DESCRIPTION
**Pull request by uthanda**
Hey, I'm not sure if you're interested, but I took your code and made some enhancements.  I started using your library in my own academic work and found there were some things missing for my purposes.  In order to scratch that itch, I forked your code and made the changes.  As this was forked from your code, I wanted to offer the changes back to you.  If you don't want them or are not interested, then I can keep them in my repo or completely fork the project into a new one.  Let me know what you would prefer.  Regardless, thanks for publishing this code as it has proven useful for me as I've been writing papers and reports for my PhD.

Also, I think I'm going to keep working on this, so you may see more changes from me.

### CODE REVIEW

**Comment by bashterm** [comment]
This is awesome! I'd be happy to merge in these changes. Are there any odds you could add some java documentation comments? If not, no worries.

I must admit I never expected to get a PR on this repository! I wrote this as a project for class in High School, and haven't done much with it recently. I guess that's the great thing about the open source community!

**Comment by uthanda** [comment]
I can add JavaDoc and let you know when it's up and running.  I was in a hurry when I made the changes and didn't go back and do that.  If you want, you can accept this change set and I can create a new PR when the comments are ready.  Up to you.

**Comment by uthanda** [comment]
Added JavaDoc, updated README.MD and added a samples section.  We can also add build the project as a Maven artifact and deploy into GitHub so people can more easily use it.  Thoughts?

**Comment by bashterm** [comment]
I like that idea. Can we build it as a maven artifact through GitHub CI?

**Comment by uthanda** [comment]
Yes, I think we can.  At least we can publish via "mvn publish" if we configure it to do so.  I've done it with one of my projects https://github.com/uthanda/zotero-java-api.  I may have to look into the GitHub CI bits and see.  Maybe for now we can just create a release we are happy with and publish as v0.1 or something and then work on the CI bits later.  Thoughts?

**Comment by bashterm** [comment]
Sounds great to me. I'll merge thanks for adding those javadocs. 

I've added you as a maintainer on the repo so you should be able to push up a maven file.

**Pull request merged**
